### ISSUE TITLE
Gatekeeper 

### ISSUE THREAD

**Issue by RichardGOV** [BVCOG-Contract-Management/BVGOG-Contract-Manager#73]
Howdy,

I was using level gatekeeper when I noticed I am unable to approve/edit contracts. However, level admin is able to do so, this means the functions are reversed. Gatekeepers should be able to approve/edit contracts that are in review. While admin should only be able to view and pull up reports. The pathway to view this issue is by logging in as level gatekeeper, select view contract, and then select any contract under review. An error will display, and the gatekeeper will be unable to approve/edit.

**Comment by TManzini** [comment]
# Reason for Behavior
Gatekeepers belong to entities
Gatekeepers can only view the contents of contracts for the entities that they are associated with

# Potential Solution
The resolution to this bug depends on your needs. 
Option 1) If you would like gatekeepers to be able to view and accept/reject contacts for entities that they are not a member of we can make a code change to enable that behavior
Option 2) if you would like to limit gatekeeper views/acceptances/rejections to only contracts that belong to their entity, then we can make it so that only their entity's contracts are displayed in the "View Contracts" list. 

@RichardGOV Let us know what would be the direction that you would prefer.

**Comment by RichardGOV** [comment]
Option 1 is the most optimal. Gatekeepers need to be able to approve all contracts going through the Contract system.
